CC = g++
HEADERS = event.h temporal_relation.h composite_event.h
SOURCES = event.cc composite_event.cc main.cc

# For ubuntu
#OUTPUT = ieminer
#OUT_OPTION = -o $(OUTPUT)

# For Mac OS X
#OUTPUT = a.out
#OUT_OPTION = 

build:
	$(CC) $(HEADERS)
	$(CC) $(SOURCES) $(OUT_OPTION)

clean:
	rm -rf *.gch
	rm -rf $(OUTPUT)
